services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: questgen:${TARGET_PLATFORM}
    platform: ${DOCKER_PLATFORM}
    command: bash
    tty: true
    working_dir: /app
