name: questgen
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - ipykernel
  - ipywidgets
  - jupyterlab
  - transformers
  - datasets
  - accelerate
  - evaluate
  - pip
  - pip:
      - torch==2.6.0
      - bitsandbytes==0.45.5
      - peft==0.15.2
      - tensorboard==2.19.0
      - standard-imghdr==3.13.0
