name: questgen
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.13
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - ipykernel
  - ipywidgets
  - jupyterlab
  - transformers
  - datasets
  - accelerate
  - evaluate
